        window._pwInitialPath = "/";



          window._pwPreviewResourceUrls = [];
          (function waterfallOptimizationScript(){window._pwPreviewResourceUrls=window._pwPreviewResourceUrls||[];if(!window._pwLoadFileRequestsCache)window._pwLoadFileRequestsCache=new Map;if(!window._pwLoadFileResolveFnCache)window._pwLoadFileResolveFnCache=new Map;window._pwSetFileCache=(fileUrl,blob)=>{if(!window._pwLoadFileResolveFnCache)throw new Error(`Variable "_pwLoadFileResolveFnCache" is undefined.`);const blobUrl=(window.URL||window.webkitURL).createObjectURL(blob);const resolveFn=window._pwLoadFileResolveFnCache.get(fileUrl);if(!resolveFn)throw new Error(`Resolve function for file "${fileUrl}" not found.`);resolveFn(blobUrl)};window._pwWaitForExplicitFileResolve=fileUrl=>{if(!window._pwLoadFileResolveFnCache)throw new Error(`Variable "_pwLoadFileResolveFnCache" is undefined.`);if(!window._pwLoadFileRequestsCache)throw new Error(`Variable "_pwLoadFileRequestsCache" is undefined.`);if(window._pwLoadFileResolveFnCache.has(fileUrl)&&window._pwLoadFileRequestsCache.has(fileUrl))return;let resolveFn=void 0;const explicitWaitPromise=new Promise(resolve=>{resolveFn=resolve});window._pwLoadFileResolveFnCache.set(fileUrl,resolveFn);window._pwLoadFileRequestsCache.set(fileUrl,explicitWaitPromise)};window._pwLoadFileFromCacheHelper=async fileUrl=>{if(!fileUrl)return void 0;try{const response=await fetch(fileUrl);if(!response.ok)return void 0;const blob=await response.blob();const blobUrl=(window.URL||window.webkitURL).createObjectURL(blob);return blobUrl}catch(error){return void 0}};window._pwLoadFileFromCache=async fileUrl=>{if(!fileUrl)return void 0;if(!window._pwLoadFileRequestsCache)throw new Error(`Variable "_pwLoadFileRequestsCache" is undefined.`);let requestPromise=window._pwLoadFileRequestsCache.get(fileUrl);if(!requestPromise){if(!window._pwLoadFileFromCacheHelper)throw new Error(`Function "_pwLoadFileFromCacheHelper" is undefined.`);requestPromise=window._pwLoadFileFromCacheHelper(fileUrl);window._pwLoadFileRequestsCache.set(fileUrl,requestPromise)}return await requestPromise};for(const explicitResourceUrl of window._pwPreviewResourceUrls)window._pwWaitForExplicitFileResolve(explicitResourceUrl)})();
        


          window._pwExecLoadingPageJavascript = () => {
            var items = document.querySelectorAll('#iw9p8'); for(var i = 0, len = items.length; i < len; i++){(function(){const _this=this;if(!_this||_this.dataset.gjsType)return;const loadingDuration=6e3;const loadingStopAtTime=4500;if(!window._pwLoadingProgressEasing){window._pwLoadingProgressEasing=x=>{return x<.5?4*x*x*x:1-Math.pow(-2*x+2,3)/2}}if(!window._pwSetLoadingProgress){window._pwSetLoadingProgress=(timeMilliseconds,progressText,circle)=>{const progress=Math.round(window._pwLoadingProgressEasing((timeMilliseconds+50)/loadingDuration)*100);if(progressText){progressText.dataset.time=`${timeMilliseconds}`;progressText.textContent=`${progress}%`}if(!circle)return;const radius=circle?parseInt(circle.getAttribute("r")||"0"):40;const c=Math.PI*(radius*2);const circleProgress=(100-progress)/100*c;circle.style.strokeDashoffset=`${circleProgress}`}}const timeId=setInterval(()=>{const progressText=Array.from(_this.children).find(el=>el.classList.contains("pwb-loading-bar-text"));const circle=_this.querySelector(`.pwb-loading-bar-circle`);const currentProgress=parseInt(progressText.dataset.time||"0");window._pwSetLoadingProgress(currentProgress+50,progressText,circle);if(currentProgress>=loadingStopAtTime){clearInterval(timeId)}},50)}.bind(items[i]))(); }
          };
          window._pwExecLoadingPageJavascript();
        